apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoopagent
spec:
  selector:
    matchLabels:
      app: hoopagent
  {{- with .Values.deploymentStrategy }}
  strategy: {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: hoopagent
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: agent
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: agent-config
