apiVersion: v1
kind: Secret
metadata:
  name: agent-config
type: Opaque
stringData:
  {{- with .Values.config.gateway }}
  HOOP_DSN: "{{ .dsn }}"
  # DEPRECATED
  HOOP_TOKEN: "{{ .token }}"
  # DEPRECATED
  HOOP_GRPCURL: "{{ .grpc_url }}"
  TLS_SERVER_NAME: "{{ .tls_server_name }}"
  {{- end }}
  AUTO_REGISTER: "{{ .Values.config.AUTO_REGISTER }}"
  LOG_ENCODING: "{{ .Values.config.LOG_ENCODING | default "json" }}"
  LOG_LEVEL: "{{ .Values.config.LOG_LEVEL | default "info" }}"
  LOG_GRPC: "{{ .Values.config.LOG_GRPC | default "0" }}"
  GODEBUG: "http2debug={{ .Values.config.LOG_GRPC | default "0" }}"