apiVersion: v1
kind: Secret
metadata:
  name: agent-config
type: Opaque
stringData:
  SERVER_ADDRESS: "{{ .Values.config.SERVER_ADDRESS }}"
  TOKEN: "{{ .Values.config.TOKEN }}"
  AUTO_REGISTER: "{{ .Values.config.AUTO_REGISTER }}"