apiVersion: v1
kind: Secret
metadata:
  name: agent-config
type: Opaque
stringData:
  SERVER_ADDRESS: "{{ .Values.config.SERVER_ADDRESS }}"
  TOKEN: "{{ .Values.config.TOKEN }}"
  AUTO_REGISTER: "{{ .Values.config.AUTO_REGISTER }}"
  LOG_ENCODING: "{{ .Values.config.LOG_ENCODING | default "json" }}"
  LOG_LEVEL: "{{ .Values.config.LOG_LEVEL | default "info" }}"