## Default values for hoop.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

# Refer to this guide for more details: https://hoop.dev/docs/self-hosting/kubernetes

image:
  gw:
    repository: hoophq/hoop
    pullPolicy: Always
    tag: latest
  agent:
    repository: hoophq/hoopdev
    pullPolicy: Always
    tag: latest

agentConfig:
  # enables a sidecar agent to the gateway.
  # it must be able to auto register itself or connect it using a grpc_url and token
  enabled: false
  AUTO_REGISTER: ''
  # debug|info|warn|error
  LOG_LEVEL: info
  # 0|1|2
  LOG_GRPC: '0'
  gateway: {}
  #   grpc_url: ''
  #   tls_server_name: ''
  #   token: ''

# hoop gateway configuration. Please refer to https://hoop.dev/docs/self-hosting
config:
  POSTGRES_DB_URI: ''
  API_URL: null
  IDP_ISSUER: null
  IDP_CLIENT_ID: null
  IDP_CLIENT_SECRET: null
  IDP_AUDIENCE: null
  # GIN_MODE: 'release|debug'
  # LOG_ENCODING: 'console|json'
  # LOG_LEVEL: 'debug|info|warn|error'
  # LOG_GRPC: "0|1|2"
  # IDP_AUDIENCE: ''
  # IDP_CUSTOM_SCOPES: ''
  # PLUGIN_AUDIT_PATH: ''
  # PLUGIN_INDEX_PATH: ''
  # SMTP_HOST: ''
  # SMTP_PORT: ''
  # SMTP_USER: ''
  # SMTP_PASS: ''
  # SLACK_CLIENT_ID: ''
  # SLACK_CLIENT_SECRET: ''
  notification: {}
  #   slackBotToken: ''
  #   bridgeUrl: ''

ingressApi:
  # -- Enables Ingress
  enabled: false
  ingressClassName: ''
  # -- Ingress annotations (values are templated)
  annotations:
    # kubernetes.io/tls-acme: "true"

  # -- Ingress hostname for API
  # host: hoop.yourdomain.tld
  # -- TLS secret name for nginx ingress
  # tlsSecret: ''

ingressGrpc:
  # -- Enables Ingress
  enabled: false
  ingressClassName: ''
  # -- Ingress annotations (values are templated)
  annotations:
    # kubernetes.io/tls-acme: "true"

  # -- Ingress hostname for gRPC
  # host: hoop.yourdomain.tld
  # -- TLS secret name for nginx ingress
  # tlsSecret: ''

persistence:
  # -- Use persistent volume for write ahead log sessions
  enabled: false
  storageClassName: null

  # -- Size of persistent volume claim
  size: 10Gi
  # annotations: {}

# -- Deployment strategy
deploymentStrategy:
  type: Recreate

# -- CPU/Memory resource requests/limits
resources:
  gw:
    limits:
      cpu: 2048m
      memory: 1Gi
    requests:
      cpu: 512m
      memory: 1Gi
