## Default values for hoop.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: hoophq/hoopdev
  pullPolicy: Always
  tag: latest


# hoop agent configuration. Please refer to https://hoop.dev/docs/configuring/agent
config:
  # name of the organization
  AUTO_REGISTER: ''
  # debug|info|warn|error
  LOG_LEVEL: info
  # 0|1|2
  LOG_GRPC: '0'
  gateway: {}
  #   grpc_url: ''
  #   tls_server_name: ''
  #   token: ''

# -- Deployment strategy
deploymentStrategy:
  type: Recreate

# -- CPU/Memory resource requests/limits
# resources:
#   limits:
#     cpu: 1024m
#     memory: 1Gi
#   requests:
#     cpu: 1024m
#     memory: 1Gi
