apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoopgateway
spec:
  selector:
    matchLabels:
      app: hoopgateway
  {{- with .Values.deploymentStrategy }}
  strategy: {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-configs.yaml") . | sha256sum }}
      labels:
        app: hoopgateway
    spec:
      containers:
      - image: "{{ .Values.image.gw.repository }}:{{ .Values.image.gw.tag }}"
        name: hoopgateway
        imagePullPolicy: {{ .Values.image.gw.pullPolicy }}
        args:
        - hoop
        - start
        - gateway
        envFrom:
        - secretRef:
            name: hoop-config
        resources:
          {{- toYaml .Values.resources.gw | nindent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - mountPath: /opt/hoop/sessions
          name: walsessions
        {{- end }}
        ports:
        - containerPort: 8010
          name: grpc
        - containerPort: 8009
          name: api
      - image: "{{ .Values.image.xtdb.repository }}:{{ .Values.image.xtdb.tag }}"
        name: xtdb
        imagePullPolicy: {{ .Values.image.xtdb.pullPolicy }}
        envFrom:
        - secretRef:
            name: xtdb-config
        resources:
          {{- toYaml .Values.resources.xtdb | nindent 10 }}
        ports:
        - containerPort: 3001
          name: api
      - image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
        name: defaultagent
        imagePullPolicy: {{ .Values.image.agent.pullPolicy }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - mountPath: /opt/hoop/sessions
          name: walsessions
        {{- end }}
        envFrom:
        - secretRef:
            name: defaultagent-config
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: walsessions
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default "walsessions" }}
      {{ end -}}