{{- if .Values.ingressApi.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- with .Values.ingressApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: hoopgateway-web
  name: hoopgateway-web
spec:
  rules:
  - host: {{ required ".ingressApi.host is required" .Values.ingressApi.host | quote }}
    http:
      paths:
      - backend:
          serviceName: hoopgateway
          servicePort: 8009
{{- end }}