{{- if .Values.ingressGrpc.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- with .Values.ingressGrpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: hoopgateway-grpc
  name: hoopgateway-grpc
spec:
  rules:
  - host: {{ required "ingressGrpc.host is required" .Values.ingressGrpc.host | quote }}
    http:
      paths:
      - backend:
          serviceName: hoopgateway
          servicePort: 8010
{{- end }}