apiVersion: v1
kind: Service
metadata:
  name: hoopgateway
spec:
  selector:
    app: hoopgateway
  ports:
    - port: 8010
      name: grpc
      protocol: TCP
      targetPort: 8010
    - port: 8009
      name: http
      protocol: TCP
      targetPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: hoopdb
spec:
  externalName: "{{ required "xtdbConfig.PG_HOST is required" .Values.xtdbConfig.PG_HOST }}"
  sessionAffinity: None
  type: ExternalName